name: CICD

on:
  push:
    branches: [ "main" ]

jobs:

  # 1️⃣ CODE
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  # 2️⃣ BUILD
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile C++
        run: g++ code.cpp -o app

  # 3️⃣ TEST
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Again
        run: g++ main.cpp -o app

      - name: Run Test
        run: |
          output=$(./app)
          echo "Output: $output"

          if [ "$output" != "Hello DevOps" ]; then
            echo "Test Failed ❌"
            exit 1
          fi

  # 4️⃣ DEPLOY
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Again
        run: g++ main.cpp -o app

      - name: Deploy (Run)
        run: |
          echo "Deploying..."
          ./app
