name: CICD

on:
  push:
    branches: [ "main" ]

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ .github/workflows/code.cpp -o app

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ code.cpp -o app
      - run: |
          output=$(./app)
          if [ "$output" != "Hello DevOps" ]; then
            exit 1
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ code.cpp -o app
      - run: ./app
