name: CICD

on:
  push:
    branches: [ "main" ]

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: g++ .github/workflows/code.cpp -o app

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: g++ .github/workflows/code.cpp -o app

      - name: Test
        run: |
          output=$(./app)

          echo "Raw Output:"
          echo "$output" | cat -A

          clean_output=$(echo "$output" | xargs)

          echo "Clean Output: [$clean_output]"

          if [ "$clean_output" != "Hello DevOps" ]; then
            echo "Test Failed ❌"
            exit 1
          else
            echo "Test Passed ✅"
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: g++ .github/workflows/code.cpp -o app

      - name: Deploy
        run: ./app
